spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist3?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: d3JybnRlaDVOSExzZnY0MzpMUE9OT0lvaW5vNG1ubw==
    access: 3600000
    refresh: 2592000000
